### ISSUE TITLE
1.20.1 not in version list

### ISSUE THREAD

**Issue by phasephasephase** [rtm516/MinecraftAppxArchiverMeta#2]
it's been a bit more than a week since this version released and the bot hasn't added the version
my mod manager depends on the version metadata here for its version changer; sorry if you don't like me doing this, but i'd like to know what happened

(https://github.com/JiayiSoftware/JiayiLauncher)

**Comment by rtm516** [comment]
I have noticed this and some other versions are missing. This is due to my bot going down and me not realising, I have started it back up and I'm trying to locate data for some of the missing versions.

1.20.1 should be on the list now
